title: "Klinefelter Oggi"
description: "Informazione indipendente e verificata sulla sindrome 47,XXY"
lang: it
url: "https://sindromediklinefelter.it"
baseurl: ""
plugins:
  - jekyll-seo-tag
exclude:
  - README.md
